Repository radis/radis, pull requests merged in 2020-04, with the labels that each got.

#83 Pull request to solve issue #82.
  radis/spectrum/compare.py
  radis/spectrum/spectrum.py
  radis/test/spectrum/test_compare.py
Labels: bug, post-process

#99 Add online tests for calculations per band, and CO2 (p,c,j,n) nonequilibrium modes
  README.rst
  radis/misc/config.py
  radis/test/__init__.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_calc.py
  radis/test/levels/test_partfunc.py
  radis/test/utils.py
Labels: ci-dev, physics

#108 Allow to calculate multiple molecules directly ( clean update)
  docs/lbl/lbl.rst
  radis/lbl/calc.py
  radis/los/slabs.py
  radis/misc/basics.py
  radis/test/lbl/test_calc.py
Labels: enhancement, interface
