Repository radis/radis, pull requests merged in 2021-07, with the labels that each got.

#303 do not try to parse comments when loading .spec (json) files
  radis/tools/database.py
Labels: performance

#304 Accelerate small spectra computation
  radis/__init__.py
  radis/lbl/factory.py
  radis/levels/partfunc.py
Labels: performance

#309 Improve radis import speed
  environment.yml
  radis/io/query.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/misc/plot.py
  radis/phys/units.py
  radis/phys/units_astropy.py
  radis/spectrum/compare.py
  radis/spectrum/spectrum.py
  radis/test/io/test_query.py
  radis/test/tools/test_gascomp.py
  radis/tools/database.py
  radis/tools/gascomp.py
  radis/tools/plot_tools.py
  radis/tools/slit.py
Labels: performance, refactor

#302 perf: dataframe refactors : drop molar mass and abundance columns
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/loader.py
Labels: performance

#315 Add: SpecDatabase Example in Gallery
  examples/plot_SpecDatabase.py
  radis/lbl/loader.py
  radis/tools/database.py
Labels: documentation

#318 Switch to memory_usage(deep=false)
  environment.yml
  radis/lbl/base.py
Labels: performance

#323 faster convolve in LDM+Voigt mode (2-30x faster on test cases)
  radis/lbl/broadening.py
Labels: performance

#326 fix import with astropy>=4.3
  radis/phys/units_astropy.py
Labels: bug

#324 introducing code quality alerts
  README.rst
Labels: ci-dev

#329 Fixes: Issue322 - update Profiler
  docs/lbl/lbl.rst
  environment.yml
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/misc/profiler.py
  radis/spectrum/spectrum.py
  radis/test/misc/test_profiler.py
  setup.py
Labels: performance
