Repository radis/radis, pull requests merged in 2021-08, with the labels that each got.

#331 Improve docs
  docs/_static/custom.css
  docs/_templates/searchbox.html
  docs/conf.py
  docs/index.rst
  docs/spectrum/database.rst
  examples/README.rst
  examples/plot_merged_large_spectrum.py
  radis/lbl/loader.py
  radis/tools/database.py
  setup.py
Labels: documentation

#325 use tuna 🐟 to generate visual/interactive performance profiles
  docs/lbl/lbl.rst
  environment.yml
  radis/lbl/factory.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/spectrum/test_utils.py
  setup.py
Labels: interface, performance

#332 Appends calculation time if same key/step is executed
  docs/lbl/lbl.rst
  radis/lbl/factory.py
  radis/misc/profiler.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/misc/test_profiler.py
  radis/test/spectrum/test_utils.py
Labels: performance

#333 Fix docs warnings, links in examples, and proper imports
  docs/conf.py
  docs/dev/_architecture.rst
  docs/dev/_install.rst
  docs/dev/_test.rst
  docs/dev/developer.rst
  docs/examples/hitran-spectra.rst
  docs/index.rst
  docs/lbl/_databases.rst
  docs/lbl/lbl.rst
  docs/references/_bibliography.rst
  docs/references/_constants.rst
  docs/references/_similar_tools.rst
  docs/references/references.rst
  docs/spectrum/_database.rst
  docs/spectrum/spectrum.rst
  examples/calculate_partition_functions_from_constants.py
  examples/calculate_partition_functions_from_tips.py
  examples/plot_blackbody.py
  examples/plot_experimental_spectrum.py
  examples/plot_nonequilibrium_co_spectrum.py
  radis/__init__.py
  radis/db/__init__.py
  radis/db/molecules.py
  radis/io/__init__.py
  radis/lbl/__init__.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/levels/partfunc.py
  radis/los/__init__.py
  radis/los/slabs.py
  radis/phys/__init__.py
  radis/spectrum/__init__.py
  radis/spectrum/utils.py
  radis/test/test_examples.py
  radis/tools/__init__.py
  radis/tools/database.py
Labels: ci-dev, documentation

#320 Add exomol support
  docs/features/features.rst
  docs/references/_bibliography.rst
  environment.yml
  examples/plot_exomol_spectrum.py
  examples/plot_hitemp_spectrum.py
  radis/__init__.py
  radis/db/__init__.py
  radis/db/classes.py
  radis/db/molecules.py
  radis/db/molparam.py
  radis/db/molparam.txt
  radis/io/exomol.py
  radis/io/exomol_utils.py
  radis/io/exomolapi.py
  radis/io/hitemp.py
  radis/io/query.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/levels/partfunc.py
  radis/los/slabs.py
  radis/misc/basics.py
  radis/misc/warning.py
  radis/spectrum/models.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/db/test_molparams.py
  radis/test/io/test_exomol.py
  radis/test/lbl/test_base.py
  radis/test/validation/test_validation_vs_specair_noneqCO.py
  setup.py
Labels: databases

#316 add on-the-fly-tabulation of calculated (eq/nonequilibrium) partition functions
  environment.yml
  radis/io/query.py
  radis/lbl/base.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/levels/partfunc.py
  radis/levels/partfunc_cdsd.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_spectrum.py
  radis/test/levels/test_partfunc.py
  setup.py
Labels: performance

#334 Add fit spectrum method
  examples/plot_fitting_method.py
  radis/lbl/factory.py
  radis/tools/fitting.py
Labels: interface

#335 Fix/doc api
  .readthedocs.yml
  docs/conf.py
  docs/index.rst
  examples/plot_hitemp_spectrum.py
  radis/__init__.py
  radis/db/__init__.py
  radis/db/molecules.py
  radis/io/__init__.py
  radis/io/hitemp.py
  radis/lbl/__init__.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/levels/__init__.py
  radis/los/__init__.py
  radis/los/slabs.py
  radis/misc/__init__.py
  radis/phys/__init__.py
  radis/phys/blackbody.py
  radis/spectrum/__init__.py
  radis/spectrum/compare.py
  radis/spectrum/spectrum.py
  radis/tools/__init__.py
  radis/tools/database.py
  radis/tools/plot_tools.py
Labels: documentation

#336 Update fitting functions
  docs/index.rst
  docs/lbl/lbl.rst
  docs/spectrum/spectrum.rst
  examples/plot_1T_fit.py
  examples/plot_experimental_spectrum.py
  examples/plot_hitemp_OH_database.py
  examples/plot_multi_temperature_fit.py
  radis/io/tools.py
  radis/lbl/factory.py
  radis/levels/partfunc.py
  radis/misc/signal.py
  radis/phys/units.py
  radis/spectrum/compare.py
  radis/spectrum/operations.py
  radis/spectrum/spectrum.py
  radis/test/spectrum/test_compare.py
  radis/test/spectrum/test_spectrum.py
  radis/tools/fitting.py
Labels: interface

#337 Fix/misc docs and imports
  examples/plot_1T_fit.py
  examples/plot_hitemp_OH_database.py
  examples/plot_multi_temperature_fit.py
  radis/__init__.py
  radis/lbl/__init__.py
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/overp.py
  radis/levels/partfunc.py
Labels: ci-dev

#281 Auto fetch hitemp for CO2 & H2O
  radis/io/cache_files.py
  radis/io/cdsd.py
  radis/io/dbmanager.py
  radis/io/hdf5.py
  radis/io/hitemp.py
  radis/io/hitran.py
  radis/misc/progress_bar.py
  radis/spectrum/spectrum.py
  radis/test/io/test_hitemp.py
  radis/test/io/test_hitran_cdsd.py
  radis/tools/line_survey.py
Labels: db:hitemp, databases

#342 Add custom abundances
  docs/examples/examples.rst
  docs/references/_bibliography.rst
  examples/calculate_partition_functions_from_tips.py
  examples/plot_custom_abundances.py
  examples/plot_linestrengths.py
  radis/db/molparam.py
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/levels/partfunc.py
  radis/spectrum/spectrum.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_loader.py
  radis/test/levels/test_partfunc.py
Labels: interface, physics

#339 add a scaling parameter to reduce the number of bins in high-dimension partition function tabulatino grids
  radis/levels/partfunc.py
  radis/test/levels/test_partfunc.py
Labels: performance

#345 Feature : show all references used to compute a Spectrum
  docs/conf.py
  docs/references/_bibliography.rst
  docs/references/references.rst
  environment.yml
  examples/cite_all_works.py
  radis/db/CO/molecules_data.json
  radis/db/CO2/molecules_data.json
  radis/db/classes.py
  radis/db/references.py
  radis/db/utils.py
  radis/lbl/broadening.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/los/slabs.py
  radis/misc/warning.py
  radis/spectrum/spectrum.py
  radis/test/tools/test_track_ref.py
  radis/tools/database.py
  radis/tools/track_ref.py
  setup.py
Labels: post-process, interface

#344 Refactor : remove separation of convolved / nonconvolved arrays in Spectrum
  docs/spectrum/spectrum.rst
  examples/plot_multi_temperature_fit.py
  examples/plot_slit_function.py
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/factory.py
  radis/lbl/overp.py
  radis/los/slabs.py
  radis/misc/arrays.py
  radis/misc/curve.py
  radis/misc/signal.py
  radis/phys/blackbody.py
  radis/spectrum/__init__.py
  radis/spectrum/compare.py
  radis/spectrum/models.py
  radis/spectrum/operations.py
  radis/spectrum/rescale.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/benchmark/radis_vs_hapi_CH4_full_spectrum.py
  radis/test/lbl/test_calc.py
  radis/test/misc/test_arrays.py
  radis/test/spectrum/test_operations.py
  radis/test/spectrum/test_spectrum.py
  radis/test/tools/test_slit.py
  radis/test/utils.py
  radis/test/validation/test_CO2_3Tvib_vs_klarenaar.py
  radis/tools/database.py
  radis/tools/fitting.py
  radis/tools/slit.py
Labels: interface, refactor

#343 Add predict_time(), make broadening_method = "voigt" as default , add default truncation of 50 cm-1
  examples/plot_1T_fit.py
  examples/plot_SpecDatabase.py
  examples/plot_exomol_spectrum.py
  examples/plot_multi_temperature_fit.py
  radis/io/dbmanager.py
  radis/io/hitemp.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/misc/arrays.py
  radis/misc/curve.py
  radis/misc/profiler.py
  radis/test/benchmark/radis_vs_hapi_CH4_full_spectrum.py
  radis/test/io/test_exomol.py
  radis/test/io/test_hitran_cdsd.py
  radis/test/lbl/test_bands.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_broadening.py
  radis/test/lbl/test_calc.py
  radis/test/lbl/test_factory.py
  radis/test/lbl/test_loader.py
  radis/test/lbl/test_overp.py
  radis/test/lbl/test_spectrum.py
  radis/test/levels/test_partfunc.py
  radis/test/misc/test_arrays.py
  radis/test/spectrum/test_spectrum.py
  radis/test/test_examples.py
  radis/test/tools/test_slit.py
  radis/test/validation/test_CO2_3Tvib_vs_klarenaar.py
  radis/test/validation/test_RADIS_vs_HAPI_line_broadening.py
  radis/test/validation/test_compare_torch_CO2.py
  radis/tools/database.py
  radis/tools/fitting.py
Labels: performance, interface

#306 Add/vaex for hitemp
  environment.yml
  radis/__init__.py
  radis/default_radis.json
  radis/io/cache_files.py
  radis/io/dbmanager.py
  radis/io/hdf5.py
  radis/io/hitemp.py
  radis/io/query.py
  radis/lbl/loader.py
  radis/test/io/test_hdf5.py
  radis/test/io/test_hitemp.py
  setup.py
Labels: performance, databases

#363 Update info messages & docs - Fixes: #351
  docs/lbl/lbl.rst
  radis/lbl/broadening.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/misc/utils.py
Labels: performance, interface

#365 Add/new color palette & update docs
  README.rst
  docs/api.rst
  docs/conf.py
  docs/radis_ico.png
  docs/radis_ico.svg
  examples/plot_1T_fit.py
  examples/plot_multi_temperature_fit.py
  radis/io/cache_files.py
  radis/io/hitemp.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/tools/database.py
  radis/tools/fitting.py
Labels: documentation
