Repository radis/radis, pull requests merged in 2021-04, with the labels that each got.

#219 Fix issue #218 (Slit dispersion bug over large spectral range)
  radis/spectrum/spectrum.py
  radis/tools/slit.py
Labels: interface

#221 Cleaning docs
  README.rst
  docs/conf.py
  docs/spectrum/database.rst
  docs/spectrum/spectrum.rst
  radis/db/molecules.py
  radis/io/query.py
Labels: documentation

#220 Improve appy_slit calculation time
  radis/test/lbl/test_calc.py
  radis/tools/slit.py
Labels: performance, post-process

#225 Add equations and references in documentation
  docs/dev/architecture.rst
  docs/features/features.rst
  docs/references/bibliography.rst
  docs/references/constants.rst
  docs/references/references.rst
  radis/db/molecules.py
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/factory.py
Labels: documentation

#227 Improve Evib/Erot fetch performances
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/factory.py
Labels: performance

#206 Add the option 'load_all' in the Database object.
  radis/db/molecules.py
  radis/spectrum/spectrum.py
  radis/test/tools/test_database.py
  radis/tools/database.py
Labels: interface, performance

#229 reduce AccuracyWarnign/AccuracyError threshold of too-coarse wavenumber grid
  radis/lbl/broadening.py
  radis/test/lbl/test_broadening.py
Labels: interface

#224 0.9.29
  .github/ISSUE_TEMPLATE/bug_report.md
  .gitignore
  CONTRIBUTING.md
  README.rst
  docs/Makefile
  docs/conf.py
  docs/dev/architecture.rst
  docs/dev/developer.rst
  docs/examples/examples.rst
  docs/features/features.rst
  docs/index.rst
  docs/lbl/gpu.rst
  docs/lbl/lbl.rst
  docs/references/bibliography.rst
  docs/references/constants.rst
  docs/references/references.rst
  docs/requirements.txt
  docs/spectrum/database.rst
  docs/spectrum/spectrum.rst
  examples/README.rst
  examples/plot_blackbody.py
  examples/plot_line_survey.py
  examples/plot_nonequilibrium_co_spectrum.py
  radis/__version__.txt
  radis/db/classes.py
  radis/db/molecules.py
  radis/io/hitemp.py
  radis/io/hitran.py
  radis/io/query.py
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/lbl/py_cuffs/py_cuffs.pyx
  radis/levels/partfunc.py
  radis/misc/config.py
  radis/phys/blackbody.py
  radis/spectrum/operations.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/benchmark/radis_vs_hapi_CH4_full_spectrum.py
  radis/test/io/test_hitemp.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_broadening.py
  radis/test/lbl/test_calc.py
  radis/test/tools/test_database.py
  radis/test/tools/test_line_survey.py
  radis/tools/database.py
  radis/tools/line_survey.py
  radis/tools/slit.py
Labels: bug, documentation, interface, performance, physics

#230 Links to source code + clickable flow chart
  docs/conf.py
  docs/dev/RADIS_flow_chart.svg
  radis/lbl/bands.py
  radis/lbl/broadening.py
  radis/lbl/factory.py
  radis/phys/blackbody.py
  radis/spectrum/equations.py
  radis/spectrum/spectrum.py
Labels: documentation

#236 Changed 'Spectral Quantity' to 'Spectral Array' at every occurrence
  docs/dev/test.rst
  docs/spectrum/spectrum.rst
Labels: documentation

#242 improve error message when file path not found
  radis/lbl/broadening.py
  radis/lbl/loader.py
  radis/misc/config.py
  radis/misc/warning.py
Labels: bug

#240 Generate default values automatically in docs
  docs/conf.py
Labels: documentation

#246 Improve doc of apply slit for trapezoidal slit function
  radis/spectrum/spectrum.py
Labels: documentation

#247 Added 'sphinx_autodoc_defaultargs' to requirements.txt
  docs/requirements.txt
Labels: documentation

#234 Fast Cython implementation of add_at()
  .gitignore
  environment.yml
  radis/__init__.py
  radis/cython/radis_cython_extensions.pyx
  radis/lbl/broadening.py
  radis/lbl/loader.py
  radis/misc/arrays.py
  radis/misc/utils.py
  radis/params.py
  radis/test/misc/test_arrays.py
  setup.py
Labels: performance

#257 fix reading of single path in config file entry
  radis/misc/config.py
Labels: bug, interface

#261 Fixes Documentation of radis.json
  README.rst
  docs/dev/test.rst
  docs/index.rst
  docs/lbl/databases.rst
  docs/lbl/lbl.rst
  radis/__init__.py
  radis/io/hitemp.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/misc/config.py
  radis/test/files/generate_test_files.py
  radis/test/io/test_hitemp.py
  radis/test/io/test_hitran_cdsd.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_broadening.py
  radis/test/lbl/test_factory.py
  radis/test/lbl/test_loader.py
  radis/test/lbl/test_spectrum.py
  radis/test/levels/test_partfunc.py
  radis/test/misc/test_arrays.py
  radis/test/misc/test_config.py
  radis/test/tools/test_slit.py
  radis/test/utils.py
  radis/test/validation/test_RADIS_vs_HAPI_line_broadening.py
  radis/test/validation/test_validation_vs_specair_noneqCO.py
  setup.cfg
Labels: documentation
