Repository radis/radis, pull requests merged in 2021-11, with the labels that each got.

#384 Prepare support for NIST extension
  radis/lbl/base.py
  radis/lbl/loader.py
  radis/spectrum/spectrum.py
  radis/test/tools/test_line_survey.py
  radis/tools/line_survey.py
Labels: databases

#389 doc improvements
  README.rst
  radis/io/hitemp.py
  radis/io/hitran.py
  radis/lbl/broadening.py
  radis/lbl/loader.py
  radis/spectrum/spectrum.py
Labels: documentation

#392 Refactor - simplify Qgas
  radis/lbl/base.py
  radis/levels/partfunc.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_calc.py
Labels: refactor

#394 Exomol update
  examples/get_molecular_parameters.py
  examples/plot_compare_CO_exomol_hitemp.py
  examples/plot_custom_abundances.py
  examples/plot_exomol_spectrum.py
  radis/db/classes.py
  radis/db/molparam.py
  radis/default_radis.json
  radis/io/cache_files.py
  radis/io/exomol.py
  radis/io/exomol_utils.py
  radis/io/query.py
  radis/lbl/base.py
  radis/lbl/calc.py
  radis/lbl/loader.py
  radis/los/slabs.py
  radis/misc/basics.py
  radis/test/db/test_molecule_lists.py
  radis/test/io/test_exomol.py
Labels: bug, physics, db:exomol

#388 Fully-Sparse wavenumber arrays
  environment.yml
  examples/plot_SpecDatabase.py
  radis/default_radis.json
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/misc/arrays.py
  radis/test/lbl/test_factory.py
  radis/test/misc/test_arrays.py
  setup.py
Labels: performance

#396 Make line_survey more flexible for extenral codes
  radis/test/test_examples.py
  radis/tools/line_survey.py
Labels: interface

#390 Improve SpecDatabase (bug correction and update)
  radis/lbl/broadening.py
  radis/lbl/loader.py
  radis/misc/basics.py
  radis/test/misc/test_arrays.py
  radis/test/misc/test_basics.py
  radis/tools/database.py
Labels: interface

#395 Dimensioned Spectrum.max() function
  radis/spectrum/models.py
  radis/spectrum/spectrum.py
  radis/test/spectrum/test_operations.py
Labels: post-process, interface

#399 Add specutils bridge
  docs/spectrum/spectrum.rst
  environment.yml
  examples/plot_specutils_processing.py
  radis/io/hitran.py
  radis/lbl/calc.py
  radis/spectrum/spectrum.py
  radis/test/files/CO2_measured_spectrum_4-5um.spec
  radis/test/files/CO_Tgas1500K_mole_fraction0.01.spec
  radis/test/files/CO_Tgas1500K_mole_fraction0.5.spec
  radis/test/files/N2C_specair_380nm.spec
  radis/tools/line_survey.py
Labels: interface

#398 Make Vaex the default HDF5 engine, add Exomol hdf5 support
  docs/lbl/lbl.rst
  docs/spectrum/spectrum.rst
  environment.yml
  examples/plot_exomol_spectrum.py
  examples/plot_hitemp_OH_database.py
  examples/plot_hitran_full_range.py
  examples/plot_merged_large_spectrum.py
  examples/plot_specutils_processing.py
  radis/default_radis.json
  radis/io/cache_files.py
  radis/io/cdsd.py
  radis/io/dbmanager.py
  radis/io/exomol.py
  radis/io/exomolapi.py
  radis/io/hdf5.py
  radis/io/hitemp.py
  radis/io/hitran.py
  radis/io/query.py
  radis/lbl/base.py
  radis/lbl/calc.py
  radis/lbl/loader.py
  radis/levels/partfunc.py
  radis/misc/config.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/io/test_hitemp.py
  radis/test/io/test_query.py
  radis/test/lbl/test_base.py
  radis/test/lbl/test_broadening.py
  radis/test/lbl/test_calc.py
  radis/test/lbl/test_loader.py
  setup.py
Labels: performance, db:exomol

#283 Updated convolve_with_slit with warnings if instrumental function has large near-zero wings
  radis/spectrum/spectrum.py
  radis/tools/slit.py
Labels: post-process, documentation

#406 temporarily deactivate Vaex in ReadTheDocs environments
  radis/io/dbmanager.py
  radis/io/exomol.py
Labels: documentation

#407 temporarily deactivate Vaex in ReadTheDocs environments
  radis/io/dbmanager.py
  radis/io/exomol.py
  radis/lbl/loader.py
Labels: documentation

#409 user custom download path
  .travis.yml
  docs/dev/_architecture.rst
  docs/features/description.rst
  docs/features/features.rst
  docs/index.rst
  docs/lbl/_databases.rst
  docs/lbl/lbl.rst
  docs/references/_bibliography.rst
  docs/references/references.rst
  environment.yml
  examples/calc_hitran_full_range.py
  radis/db/__init__.py
  radis/db/classes.py
  radis/db/references.py
  radis/default_radis.json
  radis/io/dbmanager.py
  radis/io/exomol.py
  radis/io/hitemp.py
  radis/io/hitran.py
  radis/io/query.py
  radis/lbl/calc.py
  radis/lbl/loader.py
  radis/levels/partfunc.py
  radis/spectrum/spectrum.py
  radis/test/lbl/test_calc.py
  radis/test/tools/test_track_ref.py
Labels: interface

#410 fix isotope='all' syntax when fetching HITRAN files
  radis/lbl/loader.py
Labels: bug
