Repository radis/radis, pull requests merged in 2021-01, with the labels that each got.

#163 fix "cm_1" in units of Spectrum generated before 0.9.26
  radis/tools/database.py
Labels: bug

#165 add plot_by_parts option to plot()
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/files/CO2_measured_spectrum_4-5um.spec
  radis/test/spectrum/test_spectrum.py
Labels: enhancement, post-process

#192 Improve LOS performances (SerialSlabs, etc.)
  radis/los/slabs.py
  radis/spectrum/spectrum.py
Labels: performance

#185 Faster rejection of irrelevant files
  radis/io/cdsd.py
  radis/io/hitran.py
  radis/lbl/loader.py
  radis/misc/cache_files.py
  radis/misc/warning.py
  radis/test/io/test_query.py
  radis/test/lbl/test_loader.py
  radis/test/levels/test_partfunc.py
Labels: databases, db:cdsd, db:hitemp
