Repository radis/radis, pull requests merged in 2021-06, with the labels that each got.

#277 fallback to pure Python if anything in the C-compilation breaks
  README.rst
  docs/dev/install.rst
  setup.py
Labels: bug, ci-dev

#282 Fixed wrong condition on ax varaible
  radis/misc/plot.py
Labels: bug, post-process

#265 upgrade sphinx_autodoc_defaultargs to working version
  docs/conf.py
  docs/requirements.txt
Labels: documentation

#288 update non-regression tests with new HITRAN-2020 CO2 data
  radis/test/lbl/test_calc.py
Labels: physics

#285 fix conda install dependencies,
  docs/dev/install.rst
  environment.yml
  examples/README.rst
  radis/lbl/calc.py
  radis/lbl/loader.py
Labels: ci-dev, documentation

#293 add: plot_linestrength example
  examples/plot_linestrengths.py
  radis/lbl/base.py
Labels: documentation

#298 do not load energies if equilibrium calculation in calc_spectrum
  radis/lbl/calc.py
Labels: bug, interface

#286 Add: Profiler Class
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/misc/profiler.py
Labels: ci-dev, performance, refactor

#291 Add ruler tool in plots
  .travis.yml
  radis/spectrum/compare.py
  radis/spectrum/spectrum.py
  radis/tools/plot_tools.py
  setup.py
Labels: interface, post-process

#299 Quick Fix: Statements printing on verbose = 0
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/misc/profiler.py
  radis/tools/database.py
Labels: interface

#287 perf: dataframe refactors: drop id iso Qgas columns
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/tools/line_survey.py
Labels: performance, refactor
