Repository radis/radis, pull requests merged in 2021-12, with the labels that each got.

#412 Add SpecDatabase interpolation
  examples/plot_SpecDatabase.py
  radis/io/dbmanager.py
  radis/io/hdf5.py
  radis/spectrum/spectrum.py
  radis/tools/database.py
Labels: interface

#413 get() automatically computes the spectral array if missing
  radis/lbl/factory.py
  radis/spectrum/rescale.py
  radis/spectrum/spectrum.py
Labels: interface

#380 Gpu widget new branch
  .gitignore
  .travis.yml
  MANIFEST.in
  README.rst
  docs/PULL_REQUEST_TEMPLATE.md
  docs/_templates/layout.html
  docs/_templates/searchbox.html
  docs/conf.py
  docs/examples/GPU_spectrum.png
  docs/lbl/gpu.rst
  docs/lbl/lbl.rst
  examples/calc_hitran_full_range.py
  examples/plot_gpu.py
  examples/plot_gpu_widgets.py
  radis/__init__.py
  radis/cython/cpu_gpu_agnostic.pxd
  radis/cython/radis_cython_extensions.pyx
  radis/db/CO2/gordon1966.json
  radis/db/CO2/klarenaar2017.json
  radis/default_radis.json
  radis/io/spec_hdf.py
  radis/io/tools.py
  radis/lbl/bands.py
  radis/lbl/base.py
  radis/lbl/broadening.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/gpu.cpp
  radis/lbl/gpu.cu
  radis/lbl/gpu.h
  radis/lbl/gpu.py
  radis/lbl/loader.py
  radis/lbl/overp.py
  radis/misc/arrays.py
  radis/misc/basics.py
  radis/phys/units.txt
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/files/CO2abscoeff_300K_4150_4400nm.txt
  radis/test/files/cdsd_hitemp_09_header.txt
  radis/test/files/hitran_CO2_fragment.par
  radis/test/files/hitran_CO_fragment.par
  radis/test/lbl/test_broadening.py
  radis/test/lbl/test_calc.py
  radis/test/lbl/test_factory.py
  radis/test/levels/test_partfunc.py
  radis/test/spectrum/test_utils.py
  radis/test/validation/test_compare_torch_CO2.py
  radis/tools/plot_tools.py
  setup.cfg
  setup.py
Labels: performance, interface, gpu

#414 Add support for cross-sections
  docs/spectrum/spectrum.rst
  examples/plot_compare_CO_exomol_hitemp.py
  radis/io/cdsd.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/phys/units.py
  radis/spectrum/compare.py
  radis/spectrum/rescale.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/spectrum/test_rescale.py
  radis/tools/database.py
  setup.py
Labels: interface

#416 major error in sparse algorithm if lines were not sorted
  radis/io/hdf5.py
  radis/io/hitran.py
  radis/lbl/base.py
  radis/lbl/loader.py
  radis/misc/arrays.py
Labels: bug
