Repository radis/radis, pull requests merged in 2022-04, with the labels that each got.

#445 Implement astropy unit conversion to rescale_path_length()
  radis/spectrum/rescale.py
  radis/spectrum/spectrum.py
  radis/test/spectrum/test_rescale.py
Labels: interface

#438 Templates updated
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/todo.md
  .github/ISSUE_TEMPLATE/todo.yaml
Labels: ci-dev, documentation

#447 Fixes Issue#443
  radis/lbl/factory.py
  radis/test/lbl/test_broadening.py
Labels: bug

#449 fix Readthedocs build (attempt 1)
  README.rst
  docs/conf.py
  docs/requirements.txt
  radis/lbl/base.py
Labels: documentation

#458 Fixes Hitemp whitespace parsing
  radis/io/hitran.py
Labels: databases
