Repository radis/radis, pull requests merged in 2022-05, with the labels that each got.

#464 Exomol api update
  docs/references/_bibliography.rst
  examples/plot_exomol_spectrum.py
  radis/io/dbmanager.py
  radis/io/exomol.py
  radis/io/exomolapi.py
  radis/io/hdf5.py
  radis/io/hitemp.py
  radis/io/hitran.py
Labels: refactor, db:exomol

#448 Normalize() return norm factor and units option
  radis/spectrum/spectrum.py
Labels: interface

#468 Fix/ci env
  .travis.yml
Labels: ci-dev

#466 update linesurvey & plot
  radis/spectrum/compare.py
  radis/spectrum/spectrum.py
  radis/tools/line_survey.py
Labels: post-process, interface

#462 Add GEISA database
  examples/plot_compare_CO_geisa_hitran.py
  radis/io/cache_files.py
  radis/io/dbmanager.py
  radis/io/geisa.py
  radis/io/hdf5.py
  radis/io/hitemp.py
  radis/io/tools.py
  radis/lbl/calc.py
  radis/lbl/loader.py
  radis/levels/partfunc.py
  radis/test/files/geisa_CO2_fragment.par
  radis/test/files/geisa_CO_fragment.par
  radis/test/files/geisa_H2O_fragment.par
  radis/test/files/geisa_O2_fragment.par
  radis/test/io/test_geisa.py
  radis/test/misc/test_utils.py
Labels: physics, databases

#453 Updated references.rst
  docs/references/references.rst
Labels: documentation

#471 geisa docs & line-survey
  docs/features/features.rst
  docs/index.rst
  docs/references/_bibliography.rst
  radis/__version__.txt
  radis/db/references.py
  radis/io/__init__.py
  radis/io/geisa.py
  radis/lbl/calc.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/los/slabs.py
  radis/spectrum/spectrum.py
  radis/tools/line_survey.py
Labels: interface, documentation, databases

#465 DBManager Refactor and simplification of ExoMol MdBMol
  .travis.yml
  examples/plot_compare_CO_exomol_hitemp.py
  radis/db/classes.py
  radis/io/cache_files.py
  radis/io/cdsd.py
  radis/io/dbmanager.py
  radis/io/exomol.py
  radis/io/exomolapi.py
  radis/io/geisa.py
  radis/io/hdf5.py
  radis/io/hitemp.py
  radis/io/hitran.py
  radis/lbl/loader.py
  radis/misc/basics.py
  radis/misc/utils.py
  radis/misc/warning.py
  radis/test/files/geisa_O2_fragment.par
  radis/test/io/test_exomol.py
  radis/test/io/test_hdf5.py
  radis/test/io/test_hitemp.py
Labels: refactor
