Repository radis/radis, pull requests merged in 2022-08, with the labels that each got.

#499 fix specutils i/o when dealing with wavelngths
  docs/conf.py
  radis/db/classes.py
  radis/db/molparam.py
  radis/io/hitemp.py
  radis/misc/config.py
  radis/spectrum/equations.py
  radis/spectrum/spectrum.py
  radis/test/db/test_molecule_lists.py
  radis/test/spectrum/test_spectrum_io.py
Labels: bug, interface

#498 update physics constants to NIST CODATA standards, update docs
  docs/conf.py
  docs/online/online.rst
  docs/spectrum/spectrum.rst
  examples/README.rst
  examples/calc_hitran_full_range.py
  examples/plot_SpecDatabase.py
  examples/plot_compare_CO_exomol_hitemp.py
  examples/plot_custom_abundances.py
  examples/plot_explore_database_vaex.py
  examples/plot_gpu.py
  examples/plot_gpu_widgets.py
  examples/plot_hitemp_OH_database.py
  examples/plot_multi_temperature_fit.py
  examples/plot_specutils_processing.py
  radis/io/exomol.py
  radis/io/geisa.py
  radis/io/hitemp.py
  radis/io/hitran.py
  radis/io/npy.py
  radis/lbl/factory.py
  radis/levels/partfunc.py
  radis/los/slabs.py
  radis/phys/constants.py
  radis/spectrum/operations.py
  radis/spectrum/spectrum.py
  radis/test/io/test_geisa.py
  radis/test/phys/test_blackbody.py
  radis/test/spectrum/test_operations.py
  radis/test/spectrum/test_rescale.py
  radis/test/test_phys.py
  setup.cfg
Labels: physics, documentation

#502 Remove RTD special vaex handling
  examples/plot_compare_CO_exomol_hitemp.py
  radis/io/dbmanager.py
  radis/io/exomol.py
  radis/lbl/loader.py
  radis/spectrum/compare.py
  radis/spectrum/spectrum.py
  radis/tools/database.py
Labels: documentation

#503 update chunksize test to make it faster - and RT minor perf improvement
  .travis.yml
  docs/lbl/lbl.rst
  examples/plot_explore_database_vaex.py
  radis/__init__.py
  radis/db/classes.py
  radis/db/molecules.py
  radis/default_radis.json
  radis/lbl/base.py
  radis/lbl/calc.py
  radis/levels/partfunc.py
  radis/los/slabs.py
  radis/misc/signal.py
  radis/spectrum/spectrum.py
  radis/test/lbl/test_broadening.py
Labels: performance, interface

#505 Fetch hitran update
  radis/io/dbmanager.py
  radis/io/hdf5.py
  radis/io/hitran.py
  radis/lbl/loader.py
  radis/test/io/test_hdf5.py
Labels: interface, db:hitran, databases

#512 Added warning and help improvement for get_population, update line survey, add example
  docs/spectrum/spectrum.rst
  examples/README.rst
  examples/plot_populations.py
  radis/misc/printer.py
  radis/spectrum/spectrum.py
  radis/tools/line_survey.py
Labels: documentation

#516 Refactor extra molecular parameters
  MANIFEST.in
  docs/conf.py
  docs/lbl/lbl.rst
  docs/online/online.rst
  docs/references/references.rst
  environment.yml
  radis/__init__.py
  radis/__version__.txt
  radis/db/classes.py
  radis/db/molparam.py
  radis/db/molparam.txt
  radis/db/molparams_extra.json
  radis/default_radis.json
  radis/io/exomol.py
  radis/io/hdf5.py
  radis/lbl/base.py
  radis/lbl/factory.py
  radis/lbl/loader.py
  radis/misc/arrays.py
  radis/spectrum/models.py
  radis/spectrum/utils.py
  radis/test/db/test_molparams.py
  radis/test/misc/test_utils.py
  radis/test/spectrum/test_utils.py
  setup.py
Labels: refactor

#514 Fix gpu
  docs/lbl/gpu.rst
  examples/plot_gpu.py
  examples/plot_gpu_widgets.py
  radis/lbl/base.py
  radis/lbl/factory.py
  radis/lbl/gpu.cpp
  radis/misc/arrays.py
  radis/misc/profiler.py
  radis/spectrum/equations.py
  radis/spectrum/rescale.py
  radis/spectrum/spectrum.py
  radis/test/lbl/test_gpu.py
  radis/test/spectrum/test_equations.py
  radis/tools/code_profiler.py
Labels: bug, physics
