Repository radis/radis, pull requests merged in 2023-11, with the labels that each got.

#611 New Spectrum.fit_model() routine, s.argmax(), and s.from_mat() for Matlab interface
  docs/examples/examples.rst
  docs/index.rst
  docs/lbl/lbl.rst
  docs/spectrum/spectrum.rst
  examples/calc_matlab.m
  examples/calculate_rovibrational_energies.py
  examples/plot_1T_fit.py
  examples/plot_calc_matlab.m.py
  examples/plot_chain_spectrum_edition.py
  examples/plot_explore_database_vaex.py
  examples/plot_fit_lineshape.py
  radis/__version__.txt
  radis/api/geisaapi.py
  radis/api/hitempapi.py
  radis/db/classes.py
  radis/db/molecules.py
  radis/io/exomol.py
  radis/lbl/base.py
  radis/lbl/calc.py
  radis/lbl/loader.py
  radis/lbl/overp.py
  radis/levels/partfunc.py
  radis/levels/partfunc_cdsd.py
  radis/los/slabs.py
  radis/spectrum/operations.py
  radis/spectrum/rescale.py
  radis/spectrum/spectrum.py
  radis/spectrum/utils.py
  radis/test/los/test_slabs.py
  radis/test/spectrum/test_spectrum.py
  radis/test/spectrum/test_spectrum_io.py
  radis/test/utils.py
  radis/tools/database.py
  radis/tools/fitting.py
  radis/tools/line_survey.py
  radis/tools/plot_tools.py
  radis/tools/slit.py
  radis/tools/track_ref.py
Labels: interface

#632 [Minor] Secondary xaxis & download of .states.bz2 file
  radis/api/exomolapi.py
  radis/lbl/factory.py
  radis/spectrum/spectrum.py
Labels: bug, ci-dev

#636 fixes hitemp loading error
  radis/api/hdf5.py
Labels: bug, db:hitemp
