Repository radis/radis, pull requests merged in 2024-08, with the labels that each got.

#674 A bug related to map_add
  radis/api/exomolapi.py
Labels: bug

#677 Missing broad. coef. of non-air diluents, missing requirements & 4 other fix
  .gitignore
  .travis.yml
  MANIFEST.in
  environment.yml
  examples/1_Spectra_handling/plot_full_range.py
  radis/__init__.py
  radis/__version__.txt
  radis/api/hitranapi.py
  radis/cython/radis_cython_extensions.pyx
  radis/db/classes.py
  radis/default_radis.json
  radis/lbl/broadening.py
  radis/lbl/calc.py
  radis/lbl/loader.py
  radis/misc/arrays.py
  radis/misc/warning.py
  radis/spectrum/spectrum.py
  radis/test/db/test_molecule_lists.py
  radis/test/io/test_hitemp.py
  radis/test/io/test_query.py
  radis/test/lbl/test_broadening.py
  radis/test/lbl/test_calc.py
  radis/test/levels/test_partfunc.py
  radis/test/misc/test_arrays.py
  setup.py
Labels: physics

#683 Missing GPU files in deploy and xsection rescaling
  .travis.yml
  radis/api/exomolapi.py
  radis/lbl/loader.py
  radis/spectrum/rescale.py
  radis/test/lbl/test_loader.py
  radis/test/spectrum/test_rescale.py
  setup.py
Labels: bug, ⭐⭐⭐_

#676 switch to using Einstein Coefficient for non-equilirbium linestrength calculation
  environment.yml
  radis/lbl/base.py
  radis/lbl/factory.py
  radis/test/lbl/test_calc.py
Labels: physics
