Repository radis/radis, pull requests merged in 2025-03, with the labels that each got.

#757 Sort failing tests in doc
  .travis.yml
  examples/1_Spectra_handling/compare_NO_hitran_geisa.py
  examples/1_Spectra_handling/plot_compare_CO_exomol_hitemp.py
  examples/1_Spectra_handling/plot_compare_CO_geisa_hitran.py
  radis/test/io/test_geisa.py
Labels: documentation

#747 added an option (broadf_download) in MdbExomol (not) to attempt download all of the broadening files from ExoMol server
  radis/api/exomolapi.py
Labels: enhancement

#754 Add Vaex Support for Defining alpha_ref and n_Texp in ExoMol Broadening Coefficients
  radis/api/exomolapi.py
Labels: physics

#743 Ensure HITRAN Login is Compatible with Spyder with `PyQt` Support
  radis/api/hitempapi.py
  radis/io/hitemp.py
Labels: interface

#741 Updates doc-string to `save_memory=False`
  radis/lbl/calc.py
Labels: documentation

#750 Docs: Fix Inconsistent Parameter Alignment
  docs/conf.py
Labels: documentation

#756 Calculate Download Size in `ExoMol` and Warn Users for Large Downloads in `ExoMol` & `HITEMP`
  radis/api/exomolapi.py
  radis/api/hitempapi.py
  radis/default_radis.json
Labels: interface

#630 add Unit support in Spectrum conditions, add manual Hitran cross-sections support
  MANIFEST.in
  docs/spectrum/spectrum.rst
  examples/plot_hitran_cross_section.py
  radis/api/hitranapi.py
  radis/lbl/broadening.py
  radis/los/slabs.py
  radis/spectrum/rescale.py
  radis/spectrum/spectrum.py
  radis/test/files/CH3COCH3_233.4_375.2_700.0-1780.0_13.xsc
  radis/test/io/test_hitran_cdsd.py
  radis/test/spectrum/test_operations.py
  radis/test/spectrum/test_rescale.py
  radis/test/spectrum/test_spectrum.py
  radis/test/spectrum/test_spectrum_io.py
  radis/tools/database.py
Labels: interface, db:hitran

#752 Adds different ways of calculating spectrum for multiple molecule example
  examples/1_Spectra_handling/plot_multimolecule.py
  radis/spectrum/spectrum.py
Labels: documentation

#734 Switch to pyproject.toml for installation via pip 25.0 + fewer dependencies + updates in developer guide
  .travis.yml
  CONTRIBUTING.md
  MANIFEST.in
  docs/PULL_REQUEST_TEMPLATE.md
  docs/dev/_install.rst
  docs/dev/developer.rst
  environment.yml
  pyproject.toml
  radis/test/test_sync_dependencies.py
  requirements.txt
  rst_to_md.py
  setup.py
Labels: ci-dev
